# prometheus.yml
global:
  scrape_interval: 20s
  external_labels:
    monitor: 'my-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: 'smartctl-exporter'
    static_configs:
      - targets: ['smartctl-exporter:9902']
  - job_name: 'cadvisor-exporter'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'desktop-node-exporter'
    static_configs:
      - targets: ['desktop:9100']
  - job_name: 'desktop-smartctl-exporter'
    static_configs:
      - targets: ['desktop:9902']
  - job_name: 'work-om-core'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.20.175:8086']
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets: ['alertmanager:9093']
#rule_files:
#  - 'alert.rules'
